Maptools export
elyukai/optolith-client pull request #815
Opened 2020-12-02 22:00 UTC by Lector

First version of maptools exporter. Only export XML right now and a lot of problems. (see comments)

2020-12-02 22:47 UTC, elyukai requested changes
Ich hoffe, ich habe kein TODO übersehen.

Prinzipiell würde ich mir überlegen, wie du mit den Datenstrukturen umgehst. Ich würde mich nicht auf interne Typen verlassen, da ich teilweise auch Faketypen einsetze, wo die Properties eigentlich gar nicht existieren.

2020-12-02 22:47 UTC, elyukai commented on src/App/Actions/HerolistActions.ts
> +
Das hier könntest du einfacher schreiben, da du hier keinen State abfragst oder eine asynchrone Funktion ausführst:

```suggestion
export const exportHeroAsRptok = requestHeroExportAsRptok
```

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Die Werte kannst du dir aus den Dateien unter `src/App/Selectors` ziehen. Die LE zum Beispiel bekommst du mit `getLP` aus `derivedCharacteristicsSelectors.ts`. Da sind auch die meisten anderen abgeleiteten Werte zu finden. Den Modifikator für SchiPs bekommst du aus `activatableSelectors.ts` (`getFatePointsModifier`; der Modifikator ist der Wert, der auf die Basis von 3 gerechnet wird).

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
Es so zu machen ist meinetwegen ok, allerdings kann es natürlich sein, dass sich interne Darstellungen ändern, dann hättest du hier ein Problem. Es wäre besser, wenn du die dafür vorgesehenen Funktionen aus dem Modul nimmst. Du könntest sowas machen wie:

```suggestion
  pipe_ (
    map,
    OrderedMap.elems,
    Maybe.mapMaybe(pipe (ActivatableDependent.A.id, OrderedMap.lookupF (staticMap), fmap(getName)))),
    List.intercalate(", ")
  )
```

Wobei du hier `staticMap` und `getName` noch übergeben müsstest, je nachdem, welchen Typ Entität du haben möchest. Die `ActivatableDependent`-Records halten nur die charakterspezfisichen, "dynamischen" Werte, die statischen Werte aus der Datenbank sind in separaten Records.

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  const groups: string[] = [ "Koerper", "Gesellschaft", "Natur", "Wissen", "Handwerk", "Zauber", "Rituale", "Liturgien", "Zeremonien" ]
Hier weiß ich leider nicht so genau, was du damit meinst ...?

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // "AllgemeineSF", "KampfSF", "NahkampfSF", "FernkampfSF", "Hand2HandStyles", "Hand2HandSF", "MagieSF", "KlerikaleSF"
Die statischen `SpecialAbility`-Records haben eine `gr`-Property, die auf die jeweilige Gruppe in `specialAbilityGroups` mappt.

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    // Wir brauchen hier auch ALLE Kampftechniken, auch wenn keine AP darin investiert wurden
In dem Fall würde ich über die statischen Records iterieren und dann bei jedem suchen, ob dazu ein dynamischer existiert,

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
An der Stelle würde ich `getAllCombatTechniques` in `combatTechniquesSelectors.ts` nehmen. Da bekommst du ausgerechnete AT/PA-Werte.

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
An der Stelle dürften `getMeleeWeapons`, `getRangedWeapons`, `getArmors`, `getArmorZones` und ggf. `getShieldsAndParryingWeapons` aus `equipmentSelectors.ts` weiterhelfen.

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
Da BE aktuell nicht vollständig berechnet werden *kann*, gibt es diese Berechnung nicht. Da nie klar ist, ob eine Rüstung getragen wird, wird Verbessertes Ausweichen ebenso nicht eingerechnet. Werte werden nur eingerechnet, wenn diese Werte ohne Ausnahme eingerechnet werden. An der Stelle müsstest du das also manuell machen :/

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Wir brauchen hier dann auch noch die BE + INI- und GS-Malus
Siehe oben: 

> An der Stelle dürften `getMeleeWeapons`, `getRangedWeapons`, `getArmors`, `getArmorZones` und ggf. `getShieldsAndParryingWeapons` aus `equipmentSelectors.ts` weiterhelfen.

2020-12-02 22:47 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    items[i] += `"gewicht":${value.values.weight},` // <- Hier wird das Gewicht nicht ausgegeben. Wie bekomme ich das heraus?
Ggf. muss über `getFullItem` aus `equipmentSelectors.ts` erst der vollständige Gegenstand zusammengepackt werden. Einige Gegenstände haben aber einfach auch kein Gewicht.

2020-12-02 22:59 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  const groups: string[] = [ "Koerper", "Gesellschaft", "Natur", "Wissen", "Handwerk", "Zauber", "Rituale", "Liturgien", "Zeremonien" ]
Ich hätte z.B. gerne alle Körpertalente in der Form:
{ Name, Eig1, Eig2, Eig2, FW }
Zauber und Liturgien hätte ich gerne in der selben Form aber eben unterscheidbar von anderen Fertigkeitsgruppen. Im Maptoolsframework sollen diese Gruppen in unterschiedlichen Tabs aufgelistet werden.

2020-12-02 23:04 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
Das ist auch ein Problem. Ich müsste in maptools auch wissen welche der Rüstungen im Inventar jetzt angelegt ist damit ich den Rüstungsschutz anwenden kann und die Belastung kenne. Vielleicht könnte man hier mal längerfristig nachdenken ob man im Optolithen soetwas einstellen kann. Die Druckvorschau des Charakterbogens würde ja auch davon profitieren.

2020-12-02 23:30 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
Und wo bekomme ich diese staticMap überhaupt her?

2020-12-02 23:31 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  const groups: string[] = [ "Koerper", "Gesellschaft", "Natur", "Wissen", "Handwerk", "Zauber", "Rituale", "Liturgien", "Zeremonien" ]
Möchtest du, dass die Eigenschaften dann ihren jeweiligen Namen und Wert haben?

Dann könntest du, ähnlich wie weiter oben beschrieben, zu den Talenten ihre jeweiligen dynamischen Einträge aus der Map des Charakters holen und dann ähnlich mit den drei Eigenschaften verfahren, zu denen ja die IDs im statischen Talent hinterlegt sind.

2020-12-02 23:31 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
Das ist auch angedacht: https://github.com/elyukai/optolith-client/issues/59

2020-12-04 06:42 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Sehe ich das richtig dass getFatePointsModifier gar keinen Bezug zu einem Helden hat? Wie erkennt diese Funktion zu welchem Helden die Schips abgefragt werden sollen?

2020-12-04 07:24 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    items[i] += `"gewicht":${value.values.weight},` // <- Hier wird das Gewicht nicht ausgegeben. Wie bekomme ich das heraus?
getFullItem(hero.values.belongings.values.items) will noch eine OrderedMap<string, Record<ItemTemplate>>.
Wo bekomme ich denn das schon wieder her?

2020-12-04 07:31 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
getShieldsAndParryingWeapons und getArmors wollen nur den AppState und nicht den Helden als Parameter haben. Liefern die dann alle Gegenstände von allen Helden zurück oder wie funktioniert das?

2020-12-04 09:20 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
Bleibt noch die Frage wie ich überhaupt an den Ausweichen-Wert komme.
Muss ich hier einfach GE/2 nehmen oder gibt es eine Funktion?
Verbessertes Ausweichen muss ich dann eben in maptools einrechnen

2020-12-04 09:23 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
Ich habe mich jetzt mal auf getMeleeWeapons und getRangedWeapons fokusiert. Mir ist aufgefallen dass die RangedWeapon im Gegensatz zur Melee-Weapon KEIN isImprovised-Feld hat. Laut Rüstkammer I gibt es aber durchaus improvisierte Wurfwaffen. Desweiteren würde ich Parierwaffen auch als Nahkampfwaffen eintragen. Parierwaffen sind doch IMMER auch Nahkampfwaffen oder? Gibt es eine Möglichkeit den Parierwaffen-Bonus, falls vorhanden, von einer MeleeWeapon zu bekommen?

2020-12-04 09:38 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
Sind in den Werten bereits MU und GE/KK-Bonis eingerechnet? Ich bräuchte das ohne diese Werte da ein Held ja beim Spielen einen Attributo abbekommen kann, was seinen entsprechenden Bonus erhöhen würde. Den würde ich gerne in maptools manuell einrechnen

2020-12-04 10:31 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Dass der Held mit übergeben wird, ist nur eine leichte Verbesserung der Geschwindigkeit. Prinzipiell kann der Held auch aus dem AppState extrahiert werden und das ist auch das, was aktuell noch die meisten Selektoren machen.

2020-12-04 10:32 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
Daran kommst du über `getWiki` aus `stateSelectors.ts`, der du den AppState übergeben musst.

2020-12-04 10:35 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
Ja, sind sie. Dann müsstest du dir AT/PA/FK selbst ausrechnen oder eben den Bonus an der Stelle erst herunterrechnen. Da aktuell aber mWn nichts anderes diese Werte beeinflusst, sollte selbst ausrechnen genauso gut gehen.

2020-12-04 10:36 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
> getShieldsAndParryingWeapons und getArmors wollen nur den AppState und nicht den Helden als Parameter haben. Liefern die dann alle Gegenstände von allen Helden zurück oder wie funktioniert das?

Auch hier leitet sich die Funktion den Charakter aus dem AppState ab. Insofern gilt auch das nur für den aktuell gewählten Charakter.

2020-12-04 10:39 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
> Mir ist aufgefallen dass die RangedWeapon im Gegensatz zur Melee-Weapon KEIN isImprovised-Feld hat. Laut Rüstkammer I gibt es aber durchaus improvisierte Wurfwaffen.

Eigentlich sollten sie ein solches haben ... 🤔 Jedenfalls gibt es das in der Datenbank. Ich schau da mal nach.

> Desweiteren würde ich Parierwaffen auch als Nahkampfwaffen eintragen.

Müssten sie eigentlich bereits werden ...? 🤔 

> Parierwaffen sind doch IMMER auch Nahkampfwaffen oder?

Ja,

> Gibt es eine Möglichkeit den Parierwaffen-Bonus, falls vorhanden, von einer MeleeWeapon zu bekommen?

Nein, da er immer +1 beträgt. Sobald also `isParryingWeapon` auf `true` gesetzt ist, kann man von einem +1 ausgehen.

2020-12-04 10:40 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
Das kannst du auch in der `derivedCharacteristics.ts` per `getDO` abfragen. Da sind dann Flink und Einbeinig eingerechnet.

2020-12-04 10:41 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    items[i] += `"gewicht":${value.values.weight},` // <- Hier wird das Gewicht nicht ausgegeben. Wie bekomme ich das heraus?
Die müsstest du mit `StaticData.A.items (staticData)` bekommen.

2020-12-04 10:44 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Und woher weis der AppState welcher Held gemeint ist? Ich kann mir ja vorstellen dass das funktioniert wenn der Held geöffnet ist. Ich habe den Export-Button aber in die Heldenliste eingebaut. Ob das die richtige Stelle ist kann man natürlich diskutieren.

2020-12-04 10:49 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Der AppState ist der *gesamte* Zustand der Anwendung, da ist *alles* drin, also auch der aktuell geöffnete Held. Wenn du den Export-Button in der Heldenliste hast, dann weiß das Programm aber nicht, dass du diesen Helden meinst. Prinzipiell würde es aber gehen, wenn alle Selektoren, die du verwendest, immer den Held direkt nehmen und ihn nicht erst aus dem AppState ableiten (was auch ein Grund war weshalb ich angefangen habe, dass der Charakter nicht mehr abgeleitet werden soll, sondern von außerhalb kommen muss).

Du hättest an dieser Stelle also zwei Optionen: Entweder konvertierst du die fehlenden Selektoren oder du packst den Exportbutton in den Heldenbogen-Tab. Bei Letzterem sollte sich, was den Code angeht, nicht wirklich etwas verändern, außer dass er dann in nem anderen Controller steht.

2020-12-04 10:50 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
CombatTechniqueWithRequirements enthält aber den FW nicht. Nur AT und PA.

2020-12-04 10:52 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
isParryingWeapon existiert nicht auf MeleeWeapon

2020-12-04 10:54 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
Bei Fernkampfwaffen ist der AT der FK.

2020-12-04 10:54 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // Für jede Waffe brauchen wir auch das zugehörige Kampftalent ODER die Leiteigenschaften
Okay, dann muss ich das noch fixen.

2020-12-04 11:04 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // Verbessertes Ausweichen sollte bereits eingerechnet sein. Belastung aber nicht.
passt. Verbessertes Ausweichen rechnet dann maptools

2020-12-04 11:20 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    items[i] += `"gewicht":${value.values.weight},` // <- Hier wird das Gewicht nicht ausgegeben. Wie bekomme ich das heraus?
wunderbar

2020-12-04 11:49 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
Ich habe das ganze etwas umstrukturiert. Sieht jetzt so aus:

`  xml += entry ({
    key: "Vorteile",
    value: pipe_(
      hero.values.advantages,
      OrderedMap.elems,
      Maybe.mapMaybe (pipe_ (ActivatableDependent.A.id.toString(),
                             OrderedMap.lookupF (getWiki()),
                             fmap((adv)=>{adv}))), //hier zeigt er mir keine Properties
      List.intercalate(", "))
    })`

Irgendwo ist noch ein Typfehler drin. Ich blick da aber auch nicht wirklich durch. Keine Ahnung was hier passiert.

2020-12-04 12:04 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
Ich meinte den Fertigkeitswert. Nicht den Fernkampfwert.

2020-12-04 12:07 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
- Also `pipe_` muss `pipe` sein, weil du einen Parameter aus `mapMaybe` bekommst.
- Bei `Activatable.A.id` darfst du kein `toString()` machen, weil die Funktion ja die ID aus dem Parameter lesen muss.
- `getWiki()` müsste `getWikiAdvantages (state)` sein. 
- `(adv) => {adv}` gibt `undefined` zurück, wenn du ein Objekt mit der Eigenschaft `adv` zurückgeben willst, musst du `(adv) => ({adv})` schreiben. 
- `List.intercalate` ist quasi `Array#join`. Das geht hier nicht, weil du ein Objekt zurückgibst, das einen Record enthält.

Was das ganze machen *soll*: 
Du möchtest ja die Namen für alle Vorteile bekommen. Bei einem Charakter werden aber nur die aktuellen Zustände der Vorteile gespeichert, nicht die Vorteile selbst. Daher musst du dir über die ID erst einmal den dazugehörigen Vorteil holen. Wenn es den gibt, kannst du dir z. B. per `Advantage.A.name` den Namen extrahieren – also in das `fmap` einsetzen. Damit hättest du eine Liste von Strings, die du dann mit `List.intercalate` joinen kannst.

Das generiert dir aber nur die Namen. Wenn du die Auswahloptionen auch mit ausgeben möchtest, kommst du damit nicht weit. In dem Fall würde ich dir empfehlen, mit `getAdvantagesForSheet` aus `activatableSelectors.ts` zu arbeiten. Das Ergebnis kannst mit `compressList (staticData) (list)`, wobei `list` das Ergebnis aus dem zurückgegebenen `Maybe` ist, als einzelnen String formatieren und dann speichern.

2020-12-04 12:20 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
Oh, my bad, irgendwie hatte ich FK gelesen. Doch, der FW, ist in der `stateEntry` (oder `heroEntry`?) property geschachtelt. Und dort dann in `value`.

2020-12-04 15:42 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
Also ich hab jetzt mal lange genug rumgespielt um das System der Funktionen zu verstehen. Ich hab das ganze jetzt mal aufgeteilt um die Typen ein bischen genauer analysiert die man hier braucht. Aktuell will ich mal nur den Namen herausfinden und stoße auf ein kleines Problem:

```
  const getAdvantageName = pipe (
    ActivatableDependent.A.id,
    OrderedMap.lookupF (getWikiAdvantages(state)),
    fmap ((adv: Record<Advantage>)=>{
      adv.values.name
    }))

  xml += entry ({
    key: "Vorteile",
    value: pipe_(
      hero.values.advantages,
      OrderedMap.elems, //gibt mir List<Record<ActivatableDependent>>
      fmap(getAdvantageName), //will Functor<Record<ActivatableDependent>>
      List.intercalate(", "))
    })
```

2020-12-04 18:35 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
Der untere Teil müsste so sein:

```ts
  xml += entry ({
    key: "Vorteile",
    value: pipe_(
      hero.values.advantages,
      OrderedMap.elems, 
      Maybe.mapMaybe(getAdvantageName), // mapMaybe statt fmap
      List.intercalate(", "))
    })
```

Dann sollte er eigentlich keine Fehler schmeißen …

2020-12-05 05:51 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
Das hat nichts geändert. Immer noch der gleiche Typfehler.
![grafik](https://user-images.githubusercontent.com/765587/101235156-41c84300-36c6-11eb-99a1-f538b10caf6c.png)

2020-12-05 05:55 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
So wie ich es verstanden habe müsste Maybe.mapMaybe ja das gleiche machen wie fmap nur dass die Maybe-Elemente, die nichts enthalten, quasi bei der Ausführung rausgefiltert werden. Und da ich von OrderedMap.elems keine Maybes bekomme dürfte das keinen Unterschied machen

2020-12-05 06:25 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
Aber `getAdvantageName` gibt ein `Maybe` zurück. Und das müsste ja herausgefiltert werden. Ich frage mich gerade nur, wieso er den Typ nicht richtig inferieren kann … 🤔

2020-12-05 06:28 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  })
Statt 

```
(adv: Record<Advantage>)=>{
      adv.values.name
    })
```

würde ich sonst mal 

```
Advantage.A.name
```

in `fmap` einsetzen. Ich habe eben gesehen, dass als Rückgabetyp von `getAdvantageName` offenbar `Maybe<void>` inferiert wird, was ja nun nicht wirklich stimmt.

2020-12-05 10:18 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  })
Die Kürzung hat funktioniert. getAdvantageName gibt durch die Änderung Maybe<string>zurück. Jetzt bekomme ich hier zumindest keinen Kompilierfehler mehr.

2020-12-05 10:40 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // "AllgemeineSF", "KampfSF", "NahkampfSF", "FernkampfSF", "Hand2HandStyles", "Hand2HandSF", "MagieSF", "KlerikaleSF"
Alles klar. Ich hab mich jetzt mal selbst an einem funktionalen Ausdruck versucht. Ein bischen Hilfe brauche ich noch

```
pipe_(
    hero.values.specialAbilities,
    OrderedMap.keys,
    Maybe.mapMaybe(OrderedMap.lookupF(state.values.wiki.values.specialAbilities)),
    fmap((x: Record<SpecialAbility>)=>
      ({ key: pipe_(x.values.gr,
                    OrderedMap.lookupF(state.values.wiki.values.specialAbilityGroups),
                    specialAbilityGroupForMapTool),
        value: x.values.name
      })
    )//, gruppieren nach Kategorie (geht das?) value sollte dann Kommagetrennt vereinigt werden
    //, fmap(entry)
    //, List.intercalate("")
  )
```

Ich hole mir quasi aus der wiki eine Vollständige Special-Ability und bastle mir dadraus dann einen MapToolEntry mit key: Gruppe und value: Name der SF. Was ich dann noch bräuchte wäre nach keys zu gruppieren und die values innerhalb eine Gruppe kommagetrennt zu schreiben. Gibt es dafür eine passende Funktion?

2020-12-05 12:46 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    // Die Leiteigenschaften müssen dann auch hier oder bei den Waffen ermittelt werden
alles klar.

2020-12-05 13:01 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // da hero.race ein string ist funktioniert das so nicht
Gut. Der Button wird umziehen

2020-12-07 16:32 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    List.intercalate (""))
Vielleicht hilft dir das weiter …?

```suggestion
  let xml: string = pipe_ (
    state.values.wiki.values.attributes,
    OrderedMap.elems,
    mapMaybe ((attr: Record<Attribute>) => 
      pipe_ (
        attr,
        Attribute.A.id,
        OrderedMap.lookupF (hero.values.attributes),
        fmap (stateEntry => entry ({
          key: Attribute.A.short (attr),
          value: AttributeDependent.A.value (stateEntry),
        }))
      )
    ),
    List.intercalate (""))
```

2020-12-07 17:01 UTC, elyukai requested changes

2020-12-07 17:01 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +   weaponForXML (weapon.values) // geht nicht weil rangeWeapon kein isImprovised-Feld hat
Ich habe eben den `develop`-Branch aktualisiert. `MeleeWeapon` hat jetzt `isParryingWeapon` und `RangedWeapon` hat `isImprovisedWeapon`. Improvisierte bzw. Parierwaffen sollten bereits in den jeweiligen Selektoren verfügbar sein ... 🤔

2020-12-07 18:50 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +      return "Handwerk"
das stimmt leider.
Kann ich die Zuordnung irgendwie machen ohne auf die Deutsche lokalisierung zuzugreifen?
Das maptools-Framework wird vorerst auf Deutsch bleiben und basiert auf einem DSA4.1-Framework, welches auch intern komplett auf deutschen Begriffen aufbaut. Das ist natürlich nicht schön aber ich werde das in absehbarer Zeit nicht ändern. Ich sehe aber ein dass die Export-Funktion auf allen Sprachen funktionieren sollte.

2020-12-07 18:51 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // erstmal muss aber der code weiter oben funktionieren. Das wird dann ja so ähnlich ablaufen
Vorerst mal eine Anmerkung. Ich gehe davon aus dass es analog zu den Talenten funktioniert. Nur dass ich hier nur Werte exportieren will, die auch aktiviert sind.

2020-12-07 19:09 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +      return "Handwerk"
Die Gruppen haben IDs von 1 bis 5. Generell dürften in Optolith keine deutschen IDs sein, es sind in den allermeisten Fällen numerische IDs ohne irgendwelche Namen.

2020-12-07 19:09 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  )
Wunderbar. Das hat zumindest den Kompilierfehler behoben

2020-12-07 19:14 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Wie greife ich auf den damageBonus zu? MeleeWeapon hat sowas nicht.

2020-12-07 19:16 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> -  // Hier werden zwar die Vor- und Nachteile ausgelesen aber in der Ausgabe steht nur "ActivatableDependent"
Ja das ist schon gefixt denke ich

2020-12-07 19:17 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
>  }
Das scheint nicht die Lösung gewesen zu sein...

2020-12-07 19:23 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> -  // Hier werden zwar die Vor- und Nachteile ausgelesen aber in der Ausgabe steht nur "ActivatableDependent"
Oh, my bad, ich hab nicht gecheckt, dass das rot markiert war 🙃😅🙈

2020-12-07 19:25 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
>  }
Was ist denn der Fehler?

2020-12-07 19:52 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Oh, ja, my bad, es gibt da `primary`, was immer die richtige(n) Leiteigenschaft(ein) ist/sind, und `primaryBonus`, was die dazugehörigen Schwellwerte sind.

2020-12-07 20:14 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +   }"RW":"${weapon.values.reach}",` //Reach ist eine Number. Hier soll "Kurz, Mittel, Lang" stehen, je nachdem. Wie bekomme ich das heraus?
Auch hier stellt sich die Frage wie man mit der Lokalisierung umgeht. In Maptools möchte ich IMMER die gleichen Bezeichnungen für die Reichweiten haben. Wenn in einer anderen Sprache exportiert wird sollten die auch immer gleich heißen sonst funktioniert die Erkennung nicht

2020-12-07 20:21 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +   }"RW":"${weapon.values.reach}",` //Reach ist eine Number. Hier soll "Kurz, Mittel, Lang" stehen, je nachdem. Wie bekomme ich das heraus?
Dann musst du das numerisch lösen oder von den Zahlwerten in feste Strings konvertieren. Auf Übersetzungen kannst du dich hier generell leider (?) nicht verlassen.

2020-12-08 09:06 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
>  }
![grafik](https://user-images.githubusercontent.com/765587/101462899-08e5d380-393d-11eb-8165-3a869f8ab181.png)

2020-12-08 09:08 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +   }"RW":"${weapon.values.reach}",` //Reach ist eine Number. Hier soll "Kurz, Mittel, Lang" stehen, je nachdem. Wie bekomme ich das heraus?
Wenn du mir sagst wo ich die Zuordnung finde, bzw. mir sagt welcher Wert für welche Reichweite steht kann ich das einbauen

2020-12-08 09:18 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
>  }
Ach so, groups ist ein Array von dir. Wenn du das als Liste erstellst (über den `List` constructor) oder das Array konvertierst (`List.fromArray`), sollte es gehen.

2020-12-08 09:19 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +   }"RW":"${weapon.values.reach}",` //Reach ist eine Number. Hier soll "Kurz, Mittel, Lang" stehen, je nachdem. Wie bekomme ich das heraus?
Das kannst du der Datenbank unter Reaches entnehmen: 1 für Kurz, 2 für Mittel, 3 für Lang und 4 für Überlang.

2020-12-08 09:21 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Es sind zwei Zahlen, wenn es zwei Leiteigenschaften (GE/KK) mit unterschiedlichen Schadensschwellen sind – ja, das gibt es 🙃🙃🙃

2020-12-08 09:24 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +      return "Handwerk"
Die Zuordnung kannst du in der Datenbank unter `SkillGroups` finden. Sie geht einfach von vorne nach hinten: 1 ist Körper und 5 ist Handwerk.

2020-12-08 12:28 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +      return "Handwerk"
Gut. Das wäre erledigt

2020-12-08 12:43 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
>  }
Hat geholfen. Hab aber immer noch Probleme

![grafik](https://user-images.githubusercontent.com/765587/101485402-67ba4580-395b-11eb-9b9f-2c3cd2d19dc2.png)

2020-12-08 12:54 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // In maptools kann man dann anklicken ob man die Plattenrüstung oder die Winterkleidung trägt
Ok ich habe mich jetzt mal damit beschäftigt. Komme soweit klar. Wie bekomme ich INI und GS-Abzug aus einer HitZoneArmorForView?

2020-12-08 13:19 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // In maptools kann man dann anklicken ob man die Plattenrüstung oder die Winterkleidung trägt
Was ich noch festgestellt habe: In Armor ist armor.enc ein Maybe. In HitZoneArmorForView ein number.

2020-12-08 13:43 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
>  }
List ist kein Konstruktor im OO-Sinn, du musst das `new` also weglassen, dann sollte es gehen.

Was das `filter` unten angeht: was für einen Typ hat `ungrouped`? Da müssen Strings drin sein, damit gefiltert und anschließend gejoint werden kann. Alternativ kannst du mit `mapMaybe` filtern und direkt dort einen String extrahieren, damit du `intercalate` ausführen kannst.

2020-12-08 18:17 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
>  }
wunderbar. jetzt klappts

2020-12-08 18:20 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +   }"RW":"${weapon.values.reach}",` //Reach ist eine Number. Hier soll "Kurz, Mittel, Lang" stehen, je nachdem. Wie bekomme ich das heraus?
wunderbar. und wieder ist ein Punkt erledigt

2020-12-08 18:22 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Damit hab ich jetzt überhaupt nicht gerechnet -.-
Kannst du mir dazu mal ein Beispiel geben?
Wenn das so ist muss ich in maptools auch noch ne ganze Menge umbauen. Ich habe bisher immer die Leiteigenschaft in der Kampftechnik verortet und die Schadensschwelle in der Waffe.

2020-12-09 14:16 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Ich war auch sehr "glücklich", als ich das gesehen habe … 🙃🙃🙃

Verschiedene Schadensschwellen für GE/KK kannst du zum Beispiel bei der Albernischen Bauernwehr sehen. Bei der Reitgerte ändert sich zum Beispiel auch die Leiteigenschaft selbst.

2020-12-09 14:25 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // In maptools kann man dann anklicken ob man die Plattenrüstung oder die Winterkleidung trägt
Aus einer `HitZoneArmorForView` kannst du die über `addPenalties` ziehen. Wenn das `true` ist, gibt es -1/-1, ansonsten ist es unmodifiziert.

In `HitZoneArmorForView` wird die BE generiert, für `Armor` kommt die aus der Datenbank und die hat in ihrer alten Version kein eigenes Schema für Rüstungen, weshalb dieses Feld *theoretisch* leer sein kann. *Faktisch* wird es das nicht sein, aber sicher ist sicher. Du kannst das also problemlos mit `Maybe.sum` oder `Maybe.fromMaybe (0)` auf 0 als Default setzen.

2020-12-10 07:19 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Albernische Bauernwehr habe ich gerade bestätigt. Da muss ich was umbauen.
Wo finde ich denn die Reitgerte. Regelwiki findet nix dazu. Im Optolithen ist die auch noch nicht drin.

2020-12-10 10:20 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  + `"S":${fromMaybe (0, weapon.values.schadensschwelle)},` //Wie bekomme ich die Schadensschwelle?
Ich hab die in der Optolith-Datenbank gefunden … 😅🙈 Ich schau da gleich nochmal nach; vielleicht ist die aus WdV.

2020-12-16 14:59 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  + `"Parierwaffe":${weapon.values.parryWeaponBonus}}` //Dieses Feld fehlt ja noch
Ich bin am überlegen ob das so sinnvoll ist. Auch wenn es momentan nur Parierwaffen mit +1-Bonus gibt kann doch in der nächsten Regionalbeschreibung eine mit +2 erscheinen. Ich glaube ich werde das weiterhin als number-Feld bei mir pflegen

2020-12-20 16:48 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  xml += entry ({ key: "APverfuegbar", value: "50" })
Hierfür kannst du [`getAPObjectMap`](https://github.com/elyukai/optolith-client/blob/develop/src/App/Selectors/adventurePointsSelectors.ts#L214) nehmen. Wichtig ist hier, dass es kein normaler Selector ist, sondern ein Selector, der Werte für jeden Charakter cacht. Daher musst du zusätzlich die ID des aktuellen Charakters übergeben.

2020-12-20 16:50 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +        attr1: Skill.A.check (skillFromWiki)[0], // Wie kann ich auf die einzelnen Elemente der List zugreifen?
Über `List.subscript` bzw. `List.subscriptF`.

2020-12-20 16:53 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +     }]` })
Was genau ist denn das Problem hier?

Übrigens: Die ganzen `<number>`-Angaben kannst du weglassen. Er kann mit `Maybe (0)` schon selbst inferieren, dass es ein `Maybe<number>` ist.

2020-12-20 16:55 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  //als Token wäre ein kleines runden Thumbnail passend, so wie es in der Heldenliste angezeigt wird
Hier weiß ich leider nicht so ganz, wie ich dir helfen kann. Das Bild liegt aktuell ja als base64-enkodierte Datei vor.

2020-12-21 12:45 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  //als Token wäre ein kleines runden Thumbnail passend, so wie es in der Heldenliste angezeigt wird
Erstmal wäre es gut zu wissen wie ich die Bilder überhaupt auslese. Um die encodierung kümmere ich mich dann schon irgendwie. Was auch noch gut zu wissen wäre: Auf der Profilseite wird ja nicht das komplette Bild angezeigt, sondern nur ein kreisförmiger Ausschnitt. Sowas würde sich natürlich hervorragend als Tokenbild machen. In maptools ist es üblich die Gesichter der Chars als Tokenbild auszuschneiden. Das sieht dann auf der Karte besser aus: 
![grafik](https://user-images.githubusercontent.com/765587/102778117-406b6b80-4392-11eb-9f45-c144dc5a7caa.png)
Von daher dachte ich dass ich sowohl das komplette Bild als Portrait exportiere, als auch den runden Ausschnitt als Token für die Karte. Wenn das dann soweit steht könnte man langfristig mal überlegen ob man vielleicht einen Dialog einbaut bei dem man den Kreisausschnitt frei aus dem Bild wählen kann. Aber das ist auf jeden Fall erstmal Zukunftsmusik.

2020-12-21 12:50 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +     }]` })
Naja ich möchte gerne sowohl die Gesamt, als auch Zonenrüstungen + einen Eintrag für "Keine Rüstung" kommagetrennt in die XML-Datei schreiben.
Für die beiden Rüstungsarten schnappe ich mir die entsprechende Liste und rufe für jedes Element eine Funktion auf um das ganze für den Export aufzubereiten. Danach habe ich 2 Listen aus Strings, die ich gerne vereinigen würde. Damit mein Dummy-Element auf jeden Fall noch mit enthalten ist erzeuge ich noch eine Liste mit der "Leeren Rüstung". Was genau das Problem ist weis ich auch nicht genau. VS sagt folgendes:

![grafik](https://user-images.githubusercontent.com/765587/102778784-7bba6a00-4393-11eb-980a-832c7d645257.png)

2020-12-21 13:08 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +     }]` })
Ach so, ja. `armors` ist `List<Record<Armor>>` und dein `totalArmorForXML` erwartet `Armor`. `fmap ((armor: Armor) => totalArmorForXML (armor)))` erwartet damit `List<Armor>`, bekommt aber `List<Record<Armor>`. Deine an `fmap` übergebene Funktion müsste als Parameter `armor: Record<Armor>` haben (hier drauf achten, dass `Record` auch aus der Record.ts importiert wird, sonst beschwert TS sich, dass zwei Typen für den Typ Record erwartet werden), und den könntest du dann in der Funktion so entkapseln, dass nur noch `Armor` an deine eigene Funktion übergeben wird.

Gleiches gilt für Zeile 591.

2020-12-21 13:09 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  //als Token wäre ein kleines runden Thumbnail passend, so wie es in der Heldenliste angezeigt wird
Das Bild ist bereits eingelesen und liegt im HeroModel unter `avatar` als base64-enkodiertes Bild vor, da es aktuell auch so gespeichert wird; es gibt keine separaten Bilddateien. Du musst es dir nur aus dem Record holen.

2020-12-21 13:10 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  //als Token wäre ein kleines runden Thumbnail passend, so wie es in der Heldenliste angezeigt wird
Es gibt auch nur ein Bild, das vollständige Bild wird zentriert und dient als Portrait in der Anwendung.

2020-12-21 14:26 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +     }]` })
Klappt danke

2021-01-03 14:49 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
- `async` brauchst du, wenn du `await` nutzen möchtest.
- Da du das jetzt im Heldenbogen-View machst, kannst du dir den aus dem `SheetsController` holen, da der an den durch `OwnProps` weitergereicht wird.
- Für neue Lokalisierungsangaben musst du
  1. Das JSON-Schema für die UI in der Datenbank um die notwendigen Strings erweitern
  2. Die TypeScript-Definitionsdatei um die Angaben synchron erweitern.
  3. Die entsprechenden UI-Dateien befüllen.
  Dann sollten die neuen Felder ohne Fehler nutzbar sein.

2021-01-03 15:24 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Hier versuchst du, über einen String zu mappen. Stattdessen könntest du nur die IDs extrahieren und dann über die Liste mappen.

```suggestion
    pipe_ (
      state.values.wiki.values.spells,
      OrderedMap.elems,
      Maybe.mapMaybe ((s: Record<Spell>) => pipe_ (
        s,
        Spell.A.id,
        OrderedMap.lookupF (hero.values.spells),
        fmap (buildSpell (s))
      ))
    )
```

Ich würde aber vorschlagen, es umgekehrt zu machen: Über die Daten des Helden mappen und dann die dazugehörigen Einträge im Wiki suchen. Denn: Der Held hat meist nur einen Bruchteil der verfügbaren Optionen. Du iterierst hier also mehrfach durch sehr lange Listen. Daher, mein Vorschlag wäre:

```suggestion
    pipe_ (
      hero,
      Hero.A.spells,
      OrderedMap.elems,
      Maybe.mapMaybe (heroSpell => pipe_ (
        heroSpell,
        ActivatableSkillDependent.A.id,
        OrderedMap.lookupF (StaticData.A.spells (wiki)),
        fmap (staticSpell => buildSpell (staticSpell) (heroSpell))
      ))
    )
```

Bei Liturgien die Zeilen weiter unten müsste das Problem auf gleiche Weise gelöst werden können. 👍🏻

2021-01-03 21:06 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Dafür brauche ich noch ein wenig mehr Angaben: Wo genau sind die entsprechenden Dateiein, in denen ich die Änderungen vornehme? Ich habe auch nicht verstanden wo ich den Helden herbekomme. Ich rufe die requestHeroExportAsRptok vom SheetsContainer.ts aus auf.

2021-01-03 21:08 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Was ich noch wissen müsste ist wie ich die Zauber und Liturgien entsprechend gruppieren kann. Ich hätter Zauber und Rituale gerne getrennt. Gleiches bei Liturgien und Zeremonien.

2021-01-03 21:11 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Die Dateien sind im `optolith-data` Repo. Einmal im `Schema`-Ordner das JSON-Schema und in den `xx-XX`-Unterordnern des `Data`-Ordners die tatsächlichen Strings.

Die `mapDispatchToProps` bekommt als zweiten Parameter die ownProps übergeben, genau wie in der `mapStateToProps` darüber. Darin ist der Held und den kannst du dann direkt an deine eigene Funktion übergeben.

2021-01-03 21:14 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Die haben eine `gr`-Property, danach kannst du gruppieren. `1` sind Zaubersprüche/Liturgien und `2` sind Rituale/Zeremonien. Das Filtern müsstest du zum Beispiel mit `List.partition` realisieren können.

2021-01-03 21:48 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Gibt es außer den beiden noch weitere Gruppen, die ich vielleicht beachten muss? Die Gruppierung erfolgt ja weil für die beiden Typen evtl. unterschiedliche Regelungen gelten, die ich in maptools beachten muss. So wird bei Ritualen z.B. die Probe um passende Kleidung modifiziert, was bei Zaubern nicht der Fall ist.

2021-01-03 22:55 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Und wie bekomme ich nach dem partition die 1. und die 2. Subliste?

2021-01-04 10:42 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    )))
> Gibt es außer den beiden noch weitere Gruppen, die ich vielleicht beachten muss? Die Gruppierung erfolgt ja weil für die beiden Typen evtl. unterschiedliche Regelungen gelten, die ich in maptools beachten muss. So wird bei Ritualen z.B. die Probe um passende Kleidung modifiziert, was bei Zaubern nicht der Fall ist.

Oh wait. In den `spells` des Helden sind **noch** die magischen Handlungen gespeichert. Dann geht das gar nicht über `List.partition`, sondern eher mit `List.groupByKey`. Da es dann ja mehr als zwei Gruppen sind. Welche ID welcher Gruppe zugeordnet ist, kannst du in der Datenbank auch den `SpellGroups` entnehmen.

Um deine zweite Frage trotzdem zu beantworten: Aus einem Paar kannst du mit `Tuple.fst` und `Tuple.snd` die Werte holen.

2021-01-08 06:58 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Die Texte habe ich soweit eingetragen. Was ich noch nicht verstanden habe ist wie ich an die ownProps komme wo der Held und der state drinsteht. Aktuell rufe ich Export vom SheetsContainer aus auf. Das habe ich analog zum PDF-Export gemacht. Wo ich den Helden und den state herbekomme ich mir noch nicht wirklich klar
![grafik](https://user-images.githubusercontent.com/765587/103984404-5b5a2000-5187-11eb-8ccc-ea926905fcae.png)

2021-01-08 09:54 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Wenn du dir weiter oben `mapStateToProps` anschaust, siehst du, dass es zwei Argumente bekommt: Einmal den. Gesamt-`state` der Anwendung und einmal die `ownProps`, die die Component des Containers definiert. `mapDispatchToProps` bekommt analog dazu die `dispatch`-Funktion und als zweites Argument ebenso die `ownProps`. Die tauchen bei mir nur nicht auf, weil ich sie nicht brauche und ich daher den Parameter weggelassen habe. Den kannst du aber problemlos wieder hinzufügen.

2021-01-09 09:01 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Gut damit kann ich auf jeden Fall was anfangen.

2021-01-09 13:51 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Ich habe das mal soweit abgeändert und gepusht. Irgendwie will er den Aufruf noch immer nicht machen. Vielleicht könntest du nochmal drüberschauen

2021-01-10 13:26 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Er macht es nicht, weil die Parameter nicht übereinstimmen. Wenn du aus deiner `requestExportHeroAsRptok`-Funktion den zweiten Parameter (also `state`) weglässt und stattdessen in einer Zeile direkt nach `async (dispatch, getState) => {` dann `const state = getState ()` schreibst, sollte es gehen.

2021-01-12 06:41 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Das hat das Problem nicht gelöst. Aktueller Stand ist gepusht

2021-01-12 20:03 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
In Zeile 757 machst du eine geschweifte Klammer auf. Dadurch wird immer undefined zurückgeben. Du musst aber die asynchrone Funktion zurückgeben. Dafür einfach die Klammern wegnehmen. Dann sollte es eigentlich gehen.

Falls es dann immer noch nicht geht wäre die Fehlermeldung hilfreich.

2021-01-12 20:55 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// Den Text für den Button und das Export-Fenster müsste ich für die Lokalisierung auch irgendwo eintragen. Wo mache ich das?
Ja ich glaube das hat das letzte Problem gelöst. Da ich jetzt Wochenlang in der Luft programmiert habe kommt jetzt das lustige Bugfixen :)

2021-01-17 15:28 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Die bekommst du, wenn du die Selectors aus `attibuteSelectors` benutzt. Da weiß ich aber gerade nicht, welche, aber eine hat auf jeden Fall berechnete Werte für das jeweilige Minimum/Maximum. Das müsste ich sonst später mal schauen.

2021-01-17 15:32 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> -  // TODO: Zauber/Rituale und Liturgien/Zeremonien noch herausfinden
Ich weiß nicht genau, was du hier meinst – Zauber und RItuale machst du doch bereits die Zeilen darunter 🤔 Ich bin verwirrt 🙈

2021-01-17 15:40 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +// TODO: Hier will ich die Sprachen und Schriften Extra haben
In diesem Fall hast du ja eine Liste. Ich würde mir hier die beiden Indizes der SFs per `List.findIndex` holen. Wenn der jeweilige Index vorhanden ist, kannst du mit `deleteAtPair` das Element aus der Liste entfernen und gleichzeitig dir die einzelne SF holen. Das kannst du halt mit beiden SFs gleich machen. Die IDs dafür kannst du dir aus der `Id.ts` holen und da dann `SpecialAbilityId.Languages` bzw. `SpecialAbilityId.Scripts`.

2021-02-01 14:46 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Also wenn du mir noch mitteilst welche Funktion ich aufrufen muss würde ich das gerne noch einbauen

2021-02-02 00:50 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Das müsste der `getAttributesForView`-Selector sein.

2021-02-03 05:57 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    )))
List.partition scheint aber zu funktionieren. Ändert sich da in Zukunft was oder kann ich das so lassen?

2021-02-03 05:58 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
der Scheint mir 8er-Werte auch auszulassen oder mache ich hier was falsch?
let xml: string = pipe_ (getAttributesForView (state, { hero }),
    fromMaybe (List<Record<AttributeWithRequirements>> ()),
    mapMaybe ((attr: Record<AttributeWithRequirements>) =>
      pipe_ (
        attr,
        AttributeWithRequirements.A.wikiEntry,
        Attribute.A.id,
        OrderedMap.lookupF (hero.values.attributes),
        fmap ((stateEntry: Record<AttributeDependent>) => entry ({
          key: pipe_ (attr, AttributeWithRequirements.A.wikiEntry, Attribute.A.short),
          value: AttributeDependent.A.value (stateEntry).toString (),
        }))
      )),
    List.intercalate (""))

2021-02-08 12:26 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +    )))
In Zukunft sind die Gruppen komplett getrennt voneinander. Dann brauchst du gar nicht mehr filtern. Bis dahin kannst du das so lassen! 👍🏻 Das werde ich dann wahrscheinlich auch selbst anpassen.

2021-02-08 12:28 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Ja, wenn eine Eigenschaft nicht verwendet wird ist kein Eintrag da. Dann musst du auf 8 defaulten.

2021-02-08 18:43 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Und wie sieht es aus wenn man eine Rasse exportiert deren Default nicht auf 8 liegt?

2021-02-08 18:45 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +// TODO: Hier will ich die Sprachen und Schriften Extra haben
Die Baustelle mit den Sprachen werde ich erstmal zurückstellen. Aktuell werden die ja unter Allgemeine-SFs exportiert. Das sollte für die erste Version reichen.

2021-02-08 19:24 UTC, elyukai commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Spezies verändern nur die *Maxima*, nicht die tatsächlichen Werte.

2021-03-17 20:53 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +    )))
Alles klar. Aktuell werden halt noch keine Zaubertricks und Segnungen exportiert. Ist jetzt kein Beinbruch wenn das noch nicht drin ist. Wäre aber nice.

2021-03-17 20:55 UTC, Lector commented on src/App/Utilities/MapToolExporter.ts
> +  // TODO: Hier werden Minimaleigenschaften leider noch nicht mit exportiert.
Da ich den Zwerg nicht mit CH unter 8 generieren kann verbuche ich das mal als 'passt so'.

2021-05-06 10:31 UTC, elyukai approved these changes
Kann ich die eigentlich mergen? Den Merge Conflict würde ich dann selbst lösen. Bin jetzt dabei, alle Bugs zu fixen und dann ist die 1.5.0 fertig. Gibt aber vorher nochmal Testversionen.

2021-07-27 09:21 UTC, elyukai approved these changes

2021-08-03 10:42 UTC, elyukai approved these changes

2021-08-03 10:42 UTC, merged